<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="P5CG50647LN" name="com.webcentral.test.automation.webcentraldata.temperror" tests="8" failures="3" timestamp="15 Nov 2019 17:36:26 GMT" time="16.157" errors="0">
  <testcase name="AEP_TC_1" time="1.840" classname="com.webcentral.test.automation.webcentraldata.temperror"/>
  <testcase name="AEP_TC_3" time="3.267" classname="com.webcentral.test.automation.webcentraldata.temperror"/>
  <testcase name="AEP_TC_1" time="1.681" classname="com.webcentral.test.automation.webcentraldata.temperror"/>
  <testcase name="AEP_TC_3" time="3.032" classname="com.webcentral.test.automation.webcentraldata.temperror"/>
  <testcase name="AEP_TC_1" time="1.458" classname="com.webcentral.test.automation.webcentraldata.temperror">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Link Not Found ,
	Link Not Found ">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Link Not Found ,
	Link Not Found 
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.webcentral.test.automation.Testbase.BaseTest.reportFailureproceed(BaseTest.java:444)
	at com.webcentral.test.automation.Testbase.BaseTest.validateLink(BaseTest.java:272)
	at com.webcentral.test.automation.webcentraldata.temperror.AEP_TC_1(temperror.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:969)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1148)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- AEP_TC_1 -->
  <testcase name="AEP_TC_1" time="1.532" classname="com.webcentral.test.automation.webcentraldata.temperror"/>
  <testcase name="AEP_TC_1" time="1.670" classname="com.webcentral.test.automation.webcentraldata.temperror">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Link Not Found ,
	Link Not Found ,
	Link Not Found ">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Link Not Found ,
	Link Not Found ,
	Link Not Found 
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.webcentral.test.automation.Testbase.BaseTest.reportFailureproceed(BaseTest.java:444)
	at com.webcentral.test.automation.Testbase.BaseTest.validateLink(BaseTest.java:272)
	at com.webcentral.test.automation.webcentraldata.temperror.AEP_TC_1(temperror.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:969)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1148)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- AEP_TC_1 -->
  <testcase name="AEP_TC_1" time="1.677" classname="com.webcentral.test.automation.webcentraldata.temperror">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Link Not Found ">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Link Not Found 
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.webcentral.test.automation.Testbase.BaseTest.reportFailureproceed(BaseTest.java:444)
	at com.webcentral.test.automation.Testbase.BaseTest.validateLink(BaseTest.java:272)
	at com.webcentral.test.automation.webcentraldata.temperror.AEP_TC_1(temperror.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- AEP_TC_1 -->
</testsuite> <!-- com.webcentral.test.automation.webcentraldata.temperror -->
