<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="P5CG50647LN" name="com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI" tests="9" failures="2" timestamp="18 Nov 2019 16:39:26 GMT" time="39.051" errors="0">
  <testcase name="SBC_MAINT_TC_2" time="7.328" classname="com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI"/>
  <testcase name="SBC_MAINT_TC_5" time="1.965" classname="com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI"/>
  <testcase name="SBC_MAINT_TC_1" time="1.454" classname="com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI"/>
  <testcase name="SBC_MAINT_TC_6" time="2.196" classname="com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI"/>
  <testcase name="SBC_MAINT_TC_7" time="8.789" classname="com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Object Not Found ,
	Object Not Found ">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Object Not Found ,
	Object Not Found 
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.webcentral.test.automation.Testbase.BaseTest.reportFailureproceed(BaseTest.java:450)
	at com.webcentral.test.automation.Testbase.BaseTest.getObject(BaseTest.java:222)
	at com.webcentral.test.automation.Testbase.BaseTest.validatetext(BaseTest.java:338)
	at com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI.SBC_MAINT_TC_7(SBC_MAINT_GUI.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:969)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1148)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- SBC_MAINT_TC_7 -->
  <testcase name="SBC_MAINT_TC_3" time="2.080" classname="com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI"/>
  <testcase name="SBC_MAINT_TC_7" time="4.593" classname="com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI"/>
  <testcase name="SBC_MAINT_TC_4" time="2.062" classname="com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI"/>
  <testcase name="SBC_MAINT_TC_7" time="8.584" classname="com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Object Not Found ">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Object Not Found 
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.webcentral.test.automation.Testbase.BaseTest.reportFailureproceed(BaseTest.java:450)
	at com.webcentral.test.automation.Testbase.BaseTest.getObject(BaseTest.java:222)
	at com.webcentral.test.automation.Testbase.BaseTest.validatetext(BaseTest.java:338)
	at com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI.SBC_MAINT_TC_7(SBC_MAINT_GUI.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- SBC_MAINT_TC_7 -->
</testsuite> <!-- com.webcentral.test.automation.webcentraldata.SBC_MAINT_GUI -->
