<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="P5CG50647LN" name="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk" tests="15" failures="3" timestamp="18 Nov 2019 16:39:26 GMT" time="109.951" errors="0">
  <testcase name="GRP_SGRP_XWLK_TC_9" time="6.963" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_8" time="6.806" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_10" time="7.105" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_4" time="7.030" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_1" time="1.276" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_12" time="6.920" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_3" time="12.108" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Field Not Found ,
	Field Not Found ,
	Field Not Found ">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Field Not Found ,
	Field Not Found ,
	Field Not Found 
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.webcentral.test.automation.Testbase.BaseTest.reportFailureproceed(BaseTest.java:450)
	at com.webcentral.test.automation.Testbase.BaseTest.validatefield(BaseTest.java:318)
	at com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk.GRP_SGRP_XWLK_TC_3(Group_Subgroup_Xwalk.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:969)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1148)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- GRP_SGRP_XWLK_TC_3 -->
  <testcase name="GRP_SGRP_XWLK_TC_11" time="7.051" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_13" time="9.984" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_2" time="4.236" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_6" time="6.837" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_3" time="7.978" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Field Not Found ">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Field Not Found 
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.webcentral.test.automation.Testbase.BaseTest.reportFailureproceed(BaseTest.java:450)
	at com.webcentral.test.automation.Testbase.BaseTest.validatefield(BaseTest.java:318)
	at com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk.GRP_SGRP_XWLK_TC_3(Group_Subgroup_Xwalk.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- GRP_SGRP_XWLK_TC_3 -->
  <testcase name="GRP_SGRP_XWLK_TC_5" time="6.829" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
  <testcase name="GRP_SGRP_XWLK_TC_3" time="11.979" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Field Not Found ,
	Field Not Found ">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Field Not Found ,
	Field Not Found 
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.webcentral.test.automation.Testbase.BaseTest.reportFailureproceed(BaseTest.java:450)
	at com.webcentral.test.automation.Testbase.BaseTest.validatefield(BaseTest.java:318)
	at com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk.GRP_SGRP_XWLK_TC_3(Group_Subgroup_Xwalk.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:969)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1148)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- GRP_SGRP_XWLK_TC_3 -->
  <testcase name="GRP_SGRP_XWLK_TC_7" time="6.849" classname="com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk"/>
</testsuite> <!-- com.webcentral.test.automation.webcentraldata.Group_Subgroup_Xwalk -->
